#+TITLE: Advent of Code year-template Solutions

* Instantiating Template
- copy this directory as e.g. ~2024~
  - Re-instantiate submodules in ~lib~
- inside this directory run ~make init~

* Running
- To run with Cabal, ~hpack && cabal run year-template~
  - or ~make run~
- REPL with ~hpack && cabal v2-repl~
  - or ~make repl~
- Or, inside a ~nix-shell~:
  - Run with e.g. ~cabal --enable-nix run year-template~
  - REPL with ~cabal --enable-nix v2-repl~
- To build and run with Nix manually, ~cabal2nix . > default.nix && nix-build release.nix && result/bin/year-template~

* Testing
- Tests are set up to validate the results of each day against example input and true input.
- ~cabal test~ will run the contents of ~test/TestSuite.hs~

* Adding New Modules
- For every new module added, ~year-template.cabal~ needs updating.
- We also need to run ~gen-hie . > hie.yaml~ for HLS to pick the new modules up.
- Finally, to have Nix pick up new modules, we need:
  - ~cabal2nix . > default.nix && ~cabal2nix --shell ./. >shell.nix~

* Profiling
Generate profiling stats with ~cabal v2-run --enable-profiling exes --  +RTS -p~

* Templating
~Day666.hs~ contains a template for each day. To edit this and copy it to days 1 through 25, run ~make copy-day-666~

* Inputs
Inputs are stored in ~inputs~ and we use ~TemplateHaskell~ to embed them at compile time, to avoid unneccessary ~IO~ in the solutions.
