name:                advent
version:             0.1.0.0
github:              "harryaskham/advent"
license:             BSD3
author:              "Harry Askham"
maintainer:          "harry@askham.ai"
copyright:           "2019 Harry Askham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/harryaskham/advent#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split
- regex-tdfa
- regex-tdfa-text
- time
- bytestring
- vector
- vector-split
- listsafe
- array
- lens
- mtl
- matrix
- hidden-char
- random
- pqueue
- monad-dijkstra
- dequeue
- parsec
- monad-memo
- text
- raw-strings-qq
- hint
- MissingH
- extra
- MemoTrie
- data-memocombinators
- primes
- cryptohash-md5
- utf8-string
- base16-bytestring
- parallel
- maximal-cliques
- sgd
- ad
- backprop

library:
  source-dirs: src

executables:
  advent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
